package es.ucab.entrenos.modulos.notificacion.modelos;

public enum TipoNotificacion {
    ALERTA_SISTEMA,
    NUEVA_SOLICITUD_ENTRANTE,
    ESTADO_SOLICITUD_CAMBIADO,
    TRANSACCION_ACTUALIZADA,
    MOVIMIENTO_MONEDERO,
    ACTUALIZACION_SUBASTA,
    LOGRO_DESBLOQUEADO,
    NUEVA_OFERTA_SUBASTA,
    SUBASTA_GANADA,
    SUBASTA_POR_REVISAR,
    SANCION_APLICADA,
    SUBASTA_CANCELADA
}
