@startuml

skinparam orthogonalLayoutStrategy none
skinparam DefaultFontName Arial
skinparam DefaultFontSize 12
skinparam class {
'   BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

skinparam title {
    FontSize 18
'   FontColor #2C3E50
}

skinparam frame {
    BorderColor #black
    FontColor #black
'   BackgroundColor #FAFAFA
}


title __Diagrama de clase Sprint 1 - EntreNós__

package "Diagrama de clase EntreNós"  {

'''''''''''MODULO IDENTIDAD'''''''''''

    class Usuario {
        - id: String
        - nombre: String
        - correoElectronico: String
        - telefono: String
        - descripcionPersonal: String
        - contrasenaHash: String
        - version: int
        - monedero: Monedero
        - catalogo: CatalogoUsuario
        - estado: EstadoCuenta
        - intentosFallidos: int
        - tiempoDesbloqueoMillis: long
        - primerIntentoFallidoMillis long
        - reportesFraudeValidados: int
        - urlFotoPerfil: String
        - promedioCalificacion: float
        - cantidadCalificaciones: int
        - rol: RolUsuario
        - esVecinoDestacado: boolean
        + Usuario(id: String, nombre: String, correoElectronico: String, telefono: String, descripcionPersonal: String, contrasenaHash String): Usuario
        + isCatalogoCompletado(): boolean
        + asegurarUsuarioActivo(): void
        + finalizarConfiguracionCatalogo(float: capitalSemilla): void
        + agregarHabilidadOfrecida(nuevaHabilidad: HabilidadOfrecida): void
        + actualizarHabilidadOfrecida(idInstancia: String, nuevoPrecio: int, nuevaDescripcion: String): void
        + eliminarHabilidadOfrecida(idInstancia: String): void
        + agregarNecesidad(nuevaNecesidad: NecesidadRegistrada): void
        + actualizarNecesidadRegistrada(idInstancia: String, nuevaDescripcion: String): void
        + eliminarNecesidadRegistrada(idInstancia: String): void
        + registrarIntentoFallido(): void
        + registrarInicioSesionExitoso(): void
        + aplicarSancionPorInactividadSubasta(): void
        + registrarReporteFraudeValidado(): void
        + incrementarVersion(): void
        + agregarCalificacion(calificacion: int): void
        + isAdministrador(): boolean
    }

    class Monedero {
        - creditosDisponibles: float
        - creditosComprometidos: float
        - creditosPorLogros: float
        + Monedero(creditosDisponibles: float): Monedero
        + acreditar(montoCreditos: float): void
        + acreditarLogro(montoCreditos: float): void
        + descontar(montoCreditos: float): void
        + comprometer(montoCreditos: float): void
        + liberarCompromiso(): void
        + devolverCompromiso(): void
    }

    class CatalogoUsuario {
        - completado: boolean
        + CatalogoUsuario(): CatalogoUsuario
        + marcarComoCompletado(): void
        + agregarHabilidadOfrecida(nuevaHabilidad: HabilidadOfrecida): void
        + actualizarHabilidadOfrecida(idInstancia: String, nuevoPrecio: int, nuevaDescripcion: String): void
        + agregarNecesidad(nuevaNecesidad: NecesidadRegistrada): void
        + actualizarNecesidadRegistrada(idInstancia: String, nuevaDescripcion: String): void
        + eliminarHabilidadOfrecida(idInstancia: String): void
        + eliminarNecesidadRegistrada(idInstancia: String): void
        + isCompletado(): boolean
    }

    class Habilidad {
        - id: String
        - categoria: String
        + Habilidad(id: String, categoria: String): Habilidad
        + equals(o: Object): boolean
        + hashCode(): int
    }

    class HabilidadOfrecida {
        - idInstancia: String
        - habilidadBase: Habilidad
        - precioCreditos: int
        - descripcionServicio: String
        + HabilidadOfrecida(habilidadBase: Habilidad, precioCreditos: int, descripcionServicio: String): HabilidadOfrecida
        + equals(o: Object): boolean
        + hashCode(): int
    }

    class NecesidadRegistrada {
        - idInstancia: String
        - necesidadBase: Habilidad
        - descripcionCondiciones: String
        + NecesidadRegistrada(necesidadBase: Habilidad, descripcionCondiciones: String): NecesidadRegistrada
        + equals(o: Object): boolean
        + hashCode(): int
    }

    class CorreoPermitido {
        - id: String
        - correo: String
        - fechaCreacion: long
        + CorreoPermitido(correo: String): CorreoPermitido
    }

    enum EstadoCuenta {
        ACTIVO
        BLOQUEADO_SEGURIDAD
        SUSPENDIDO_FRAUDE
        SUSPENDIDO_SUBASTA
    }

    enum RolUsuario {
        ADMINISTRADOR
        MIEMBRO_COMUNIDAD
    }

'''''''''''MODULO PUBLICACION'''''''''''

    class Publicacion {
        - idPublicacion: String
        - idUsuario: String
        - tipoPublicacion: String
        - nombreServicio: String
        - descripcion: String
        - precioCreditos: int
        - disponible: boolean
        - idInstanciaCatalogo: String
        - version: int
        + Publicacion(idUsuario: String, tipoPublicacion: String, nombreServicio: String, descripcion: String, precioCreditos: int): Publicacion
    }

    class Transaccion {
        - idTransaccion: String
        - idPublicacion: String
        - idOfertante: String
        - idDemandante: String
        - estado: EstadoTransaccion
        - creditosComprometidos: int
        - confirmacionOfertante: boolean
        - confirmacionDemandante: boolean
        - fechaCreacion: long
        - idIncidencia: String
        - idSolicitanteCancelacion: String
        - motivoCancelacion: String
        - cancelacionAceptada: boolean
        - version: int version
        + Transaccion(idPublicacion: String, idOfertante: String, idDemandante: String, creditosComprometidos: int)
        + confirmarEntregaOfertante(): void
        + confirmarRecepcionDemandante(): void
        + verificarCompletitud(): void
        + solicitarCancelacion(idSolicitante: String, motivoCancelacion: String): void
        + aceptarCancelacion(): void
        + rehusarCancelacion(): void
        + asignarIncidencia(idIncidencia: String): void
    }

    class Solicitud {
        - idSolicitud: String
        - idPublicacion: String
        - idSolicitante: String
        - estado: String
        - fechaCreacion: long
        - fechaLimiteRespuesta: long
        - version: int
        + Solicitud(idPublicacion: String, idSolicitante: String): Solicitud
        + aceptar(): void
        + rechazar(): void
        + cancelar(): void
        + expirar(): void
        + haExpirado(): boolean
    }

    class MotivoCancelacion {
        - String id
        - String descripcion
        - boolean activo
        + MotivoCancelacion(id: String, descripcion: String)
    }

    enum EstadoTransaccion {
        PENDIENTE
        INICIADA
        FINALIZADA
        RECHAZADA
        EN_DISPUTA
    }

'''''''''''MODULO RESENA'''''''''''

    class Resena {
        - idResena: String
        - idTransaccion: String
        - idEmisor: String
        - idReceptor: String
        - calificacion: int
        - fechaCreacion: long
        - version: int
        + Resena(idResena: String, idTransaccion: String, idEmisor: String, idReceptor: String, calificacion: int): Resena
    }

'''''''''''MODULO SUBASTA'''''''''''

    class Subasta {
        - id: String
        - idPropietario: String
        - nombreActivo: String
        - descripcion: String
        - estadoFisico: EstadoFisico
        - imagenesUrls: List<String>
        - fechaInicio: LocalDateTime
        - fechaFinalizacionLicitacion: LocalDateTime
        - estado: EstadoSubasta
        - idPropuestaGanadora: String
        - propietarioConfirmoEntrega: boolean
        - boolean ganadorConfirmoEntrega
        - version: int
        + Subasta(idPropietario: String, nombreActivo: String, descripcion: String, estadoFisico: EstadoFisico, imagenesUrls: List<String>, fechaFinalizacionLicitacion: LocalDateTime): Subasta
        + registrarPropuesta(nuevaPropuesta: Propuesta): void
        + adjudicarGanador(idPropuesta: String): void
        + cancelarSubasta(): void
        + cerrarFaseLicitacion(): void
        + cancelarSubastaDesierta(): void
        + incrementarVersion(): void
        + editarPropuesta(idPropuesta: String, idPostor: String, nuevosBienes: List<BienOfrecido>, nuevasImagenes: List<String>): void
        + retirarPropuesta(idPropuesta: String, idPostor: String): void
    }

    class Propuesta {
    - idPropuesta: String
    - idSubasta: String
    - idPostor: String
    - descripcion: String
    - estadoPropuesta: EstadoPropuesta
    - estadoFisico: EstadoFisico
    - imagenesUrls: List<String>
    - fechaPropuesta: LocalDateTime
    + Propuesta(idPostor: String, idSubasta: String, bienesOfrecidos: List<BienOfrecido>, descripcion: String, estadoFisico: EstadoFisico, imagenesUrls: List<String>): Propuesta
    }

    class BienOfrecido {
        - nombre: String
        - cantidad: int
        + BienOfrecido(nombre: String, cantidad: int): BienOfrecido
    }

    enum EstadoFisico {
        NUEVO
        USADO
        REPARADO
    }

    enum EstadoPropuesta {
        EN_EVALUACION
        ACEPTADA
        RECHAZADA
    }

    enum EstadoSubasta {
        ACTIVA
        ESPERANDO_DECISION
        ADJUDICADA_INTERCAMBIO_PENDIENTE
        FINALIZADA_CON_EXITO
        CANCELADA
        CERRADA_POR_INACTIVIDAD
    }

'''''''''''SECCION NOTIFICACION'''''''''''

    class Notificacion {
        - idNotificacion: String
        - idRemitente: String
        - idDestinatario: String
        - mensaje: String
        - tipo: TipoNotificacion
        - estadoLectura: boolean
        - fechaCreacion: long
        - idReferencia: String
        - idReferenciaAuxiliar: String
        + Notificacion(idRemitente: String, idDestinatario: String, mensaje: String, tipo: TipoNotificacion, idReferencia: String, idReferenciaAuxiliar: String): Notificacion
    }

    enum TipoNotificacion {
        ALERTA_SISTEMA
        NUEVA_SOLICITUD_ENTRANTE
        ESTADO_SOLICITUD_CAMBIADO
        TRANSACCION_ACTUALIZADA
        MOVIMIENTO_MONEDERO
        ACTUALIZACION_SUBASTA
        LOGRO_DESBLOQUEADO
        NUEVA_OFERTA_SUBASTA
        SUBASTA_GANADA
        SUBASTA_POR_REVISAR
        SANCION_APLICADA
        SUBASTA_CANCELADA
   }

}

' --- IDENTIDAD Y CATÁLOGO (HU 1) ---
Usuario "1" *--- "1" Monedero
Usuario "1" --- "1" CatalogoUsuario
CatalogoUsuario "1" *-- "0..*" HabilidadOfrecida
CatalogoUsuario "1" *---  "0..*" NecesidadRegistrada
HabilidadOfrecida "0..*" --> "1" Habilidad
NecesidadRegistrada "0..*" --> "1" Habilidad

' --- RELACIONES DE PUBLICACIÓN (HU 2) ---
HabilidadOfrecida "1" --right "1" Publicacion : "genera >"
NecesidadRegistrada "1" --right "1" Publicacion : "genera >"

' --- FLUJO DE SERVICIOS (HU 3) ---
Usuario "1" -- "0..*" Solicitud : "realiza >"
Solicitud "0..*" --- "1" Publicacion : "envía <"
Solicitud "1" -- "0..1" Transaccion : "genera >"
Usuario "2" -- "0..*" Transaccion : "participa en >"
Transaccion "1" -- "1" Resena : "genera >"

' --- FLUJO DE SUBASTAS - VARIANTE 3 (HU 4 y HU 5) ---
Usuario "1" -- "0..*" Subasta : "publica >"
Subasta "1" *-- "0..*" Propuesta
Propuesta "0..*" -- "1" Usuario : "efectuada por >"
Propuesta "1" *-- "1..*" BienOfrecido

}

@enduml